"""initial schema

Revision ID: 880330f5b08d
Revises:
Create Date: 2026-08-30 09:54:18.515486

Mirrors docs/reference/db-schema.md's DDL 1:1 via app.db.models. Written by hand
(not autogenerated) because there is no live Postgres available locally --
validated with `alembic upgrade head --sql` (offline mode) instead.
"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '880330f5b08d'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "users",
        sa.Column("id", postgresql.UUID(as_uuid=True), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("phone_e164", sa.Text(), nullable=False),
        sa.Column("phone_verified_at", sa.DateTime(timezone=True)),
        sa.Column("email", sa.Text()),
        sa.Column("display_name", sa.Text(), nullable=False),
        sa.Column("birth_date", sa.Date()),
        sa.Column("kakao_sub", sa.Text()),
        sa.Column("tier", sa.Text(), server_default="FREE", nullable=False),
        sa.Column("storage_quota_bytes", sa.BigInteger(), server_default="209715200", nullable=False),
        sa.Column("storage_used_bytes", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("status", sa.Text(), server_default="ACTIVE", nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("phone_e164"),
        sa.UniqueConstraint("kakao_sub"),
    )

    op.create_table(
        "consents",
        sa.Column("id", postgresql.UUID(as_uuid=True), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("version", sa.Text(), nullable=False),
        sa.Column("granted", sa.Boolean(), nullable=False),
        sa.Column("ip", postgresql.INET()),
        sa.Column("user_agent", sa.Text()),
        sa.Column("granted_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_consents_user_id", "consents", ["user_id", "kind", "granted_at"])

    op.create_table(
        "recipients",
        sa.Column("id", postgresql.UUID(as_uuid=True), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("owner_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("display_name", sa.Text(), nullable=False),
        sa.Column("relation", sa.Text()),
        sa.Column("phone_e164", sa.Text()),
        sa.Column("email", sa.Text()),
        sa.Column("blocked_at", sa.DateTime(timezone=True)),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "phone_e164 IS NOT NULL OR email IS NOT NULL", name="ck_recipients_phone_or_email"
        ),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_recipients_owner_id", "recipients", ["owner_id"])

    op.create_table(
        "capsules",
        sa.Column("id", postgresql.UUID(as_uuid=True), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("owner_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("body_ciphertext", sa.LargeBinary()),
        sa.Column("body_nonce", sa.LargeBinary()),
        sa.Column("dek_wrapped", sa.LargeBinary()),
        sa.Column("content_hash", sa.Text()),
        sa.Column("trigger_type", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), server_default="DRAFT", nullable=False),
        sa.Column("sealed_at", sa.DateTime(timezone=True)),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_capsules_owner_id", "capsules", ["owner_id", "status"])

    op.create_table(
        "capsule_triggers",
        sa.Column("capsule_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("fire_at", sa.DateTime(timezone=True)),
        sa.Column("recurrence_rule", sa.Text()),
        sa.Column("recurrence_until", sa.Date()),
        sa.Column("require_confirm", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("confirm_sent_at", sa.DateTime(timezone=True)),
        sa.Column("confirmed_at", sa.DateTime(timezone=True)),
        sa.Column("auto_defer_days", sa.Integer(), server_default="30", nullable=False),
        sa.Column("next_fire_at", sa.DateTime(timezone=True)),
        sa.ForeignKeyConstraint(["capsule_id"], ["capsules.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("capsule_id"),
    )
    op.create_index(
        "ix_capsule_triggers_next_fire_at",
        "capsule_triggers",
        ["next_fire_at"],
        postgresql_where=sa.text("next_fire_at IS NOT NULL"),
    )

    op.create_table(
        "capsule_recipients",
        sa.Column("capsule_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("recipient_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("personal_note", sa.Text()),
        sa.ForeignKeyConstraint(["capsule_id"], ["capsules.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["recipient_id"], ["recipients.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("capsule_id", "recipient_id"),
    )

    op.create_table(
        "media_assets",
        sa.Column("id", postgresql.UUID(as_uuid=True), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("capsule_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("object_key", sa.Text(), nullable=False),
        sa.Column("mime_type", sa.Text(), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("duration_sec", sa.Integer()),
        sa.Column("dek_wrapped", sa.LargeBinary()),
        sa.Column("sha256", sa.Text()),
        sa.Column("upload_status", sa.Text(), server_default="PENDING", nullable=False),
        sa.Column("transcript", sa.Text()),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["capsule_id"], ["capsules.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_media_assets_capsule_id", "media_assets", ["capsule_id"])

    op.create_table(
        "deliveries",
        sa.Column("id", postgresql.UUID(as_uuid=True), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("capsule_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("recipient_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("occurrence_no", sa.Integer(), server_default="1", nullable=False),
        sa.Column("status", sa.Text(), server_default="PENDING", nullable=False),
        sa.Column("channel", sa.Text()),
        sa.Column("access_token_hash", sa.Text(), nullable=False),
        sa.Column("token_expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("notified_at", sa.DateTime(timezone=True)),
        sa.Column("opened_at", sa.DateTime(timezone=True)),
        sa.Column("declined_at", sa.DateTime(timezone=True)),
        sa.Column("retry_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("idempotency_key", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["capsule_id"], ["capsules.id"]),
        sa.ForeignKeyConstraint(["recipient_id"], ["recipients.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("idempotency_key"),
    )
    op.create_index("ix_deliveries_status", "deliveries", ["status", "created_at"])

    op.create_table(
        "delivery_events",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("delivery_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("event", sa.Text(), nullable=False),
        sa.Column("payload", postgresql.JSONB()),
        sa.Column("occurred_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["delivery_id"], ["deliveries.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_table(
        "death_claims",
        sa.Column("id", postgresql.UUID(as_uuid=True), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("subject_user_id", postgresql.UUID(as_uuid=True)),
        sa.Column("subject_lookup_hash", sa.Text(), nullable=False),
        sa.Column("claimant_name", sa.Text(), nullable=False),
        sa.Column("claimant_phone", sa.Text(), nullable=False),
        sa.Column("relation", sa.Text(), nullable=False),
        sa.Column("evidence_key", sa.Text()),
        sa.Column("evidence_type", sa.Text()),
        sa.Column("status", sa.Text(), server_default="SUBMITTED", nullable=False),
        sa.Column("reviewer_note", sa.Text()),
        sa.Column("reviewed_by", postgresql.UUID(as_uuid=True)),
        sa.Column("reviewed_at", sa.DateTime(timezone=True)),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["subject_user_id"], ["users.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_death_claims_subject_lookup_hash", "death_claims", ["subject_lookup_hash"])

    op.create_table(
        "ai_jobs",
        sa.Column("id", postgresql.UUID(as_uuid=True), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("ref_type", sa.Text(), nullable=False),
        sa.Column("ref_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("status", sa.Text(), server_default="QUEUED", nullable=False),
        sa.Column("request", postgresql.JSONB()),
        sa.Column("result", postgresql.JSONB()),
        sa.Column("error", sa.Text()),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True)),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_table(
        "audit_logs",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("actor_type", sa.Text(), nullable=False),
        sa.Column("actor_id", sa.Text()),
        sa.Column("action", sa.Text(), nullable=False),
        sa.Column("target", sa.Text()),
        sa.Column("ip", postgresql.INET()),
        sa.Column("detail", postgresql.JSONB()),
        sa.Column("at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )


def downgrade() -> None:
    op.drop_table("audit_logs")
    op.drop_table("ai_jobs")
    op.drop_table("death_claims")
    op.drop_table("delivery_events")
    op.drop_table("deliveries")
    op.drop_table("media_assets")
    op.drop_table("capsule_recipients")
    op.drop_table("capsule_triggers")
    op.drop_table("capsules")
    op.drop_table("recipients")
    op.drop_table("consents")
    op.drop_table("users")
